# -*- coding: utf-8 -*-
"""
生成 libs.pri: 列出所有需要静态链接的库 (相对路径, 按字母序)

布局:
  - OCR 静态库: 本目录 RapidOcrOnnxStatic.lib
  - ORT/OpenCV 静态库: 上级 ../RapidOcrEmbed/ 下

排除 (与 OnnxRuntimeConfig.cmake 一致):
  - onnxruntime_providers_shared.lib (DLL 导入库)
  - libprotoc.lib (protobuf 编译器, 运行时不需要)
  - libprotobuf-lite.lib (与 libprotobuf.lib 符号冲突)

⚠️ 额外排除 (已知冲突):
  - libjpeg-turbo.lib: 与 Qt JPEG 符号冲突, 静态链接时 QPixmap 加载 JPEG 闪退
    解决: OCR 用 BMP 格式, 不需要 JPEG codec; Qt 自带 JPEG 给 QPixmap 用
    参见: rename_jpeg_symbols.py (如需恢复 OpenCV JPEG 能力)

用法: python gen_libs_pri.py
"""
import os
import glob

# 本目录 (ocr-qt-cpp)
HERE = os.path.dirname(os.path.abspath(__file__))
# 上级 RapidOcrEmbed 目录 (含 onnxruntime-static / opencv-static)
BASE = os.path.normpath(os.path.join(HERE, "..", "RapidOcrEmbed"))

ORT_DIR = os.path.join(BASE, "onnxruntime-static", "windows-x64", "lib")
OPENCV_DIR = os.path.join(BASE, "opencv-static", "windows-x64", "x64", "vc16", "staticlib")
OCR_LIB = os.path.join(HERE, "libs", "RapidOcrOnnxStatic.lib")
MNN_LIB = os.path.join(HERE, "libs", "MNN.lib")
MUPDF_LIB = os.path.join(HERE, "libs", "mupdf.lib")
# Qt JPEG 插件 (必须在 mupdf.lib 之前链接，避免符号冲突)
# 使用环境变量 QT_STATIC_PATH 或默认路径
QT_STATIC_PATH = os.environ.get("QT_STATIC_PATH", r"C:\Qt\5.15.2\msvc2019-x64-static")
QT_JPEG_LIB = os.path.join(QT_STATIC_PATH, "plugins", "imageformats", "qjpeg.lib")
OUT = os.path.join(HERE, "libs.pri")

# qmake 相对路径前缀 (相对于 .pro 文件所在目录)
# $$PWD 表示 .pro 文件所在目录
QMAKE_PWD = "$$PWD"

EXCLUDE_ORT = {
    "onnxruntime_providers_shared.lib",
    "libprotoc.lib",
    "libprotobuf-lite.lib",
}

# ========================================================================
# ⚠️ 重要: JPEG 库符号冲突解决方案
# ========================================================================
# MuPDF 的 mupdf.lib 内置了 libjpeg-turbo (jpeg_* 符号)
# Qt 的 qjpeg.lib 也定义了 jpeg_* 符号
#
# 解决方案: 让 Qt 的 qjpeg.lib 在 mupdf.lib 之前链接
# 这样链接器优先使用 Qt 的 JPEG 实现，避免 JPG 加载闪退
# MuPDF 的 PDF 处理也能正常工作（两者都是 libjpeg-turbo）
# ========================================================================
EXCLUDE_OPENCV = {
    "libjpeg-turbo.lib",  # 与 Qt JPEG 冲突
}


def to_qmake_rel(abs_path, base_dir):
    """将绝对路径转换为 qmake 相对路径 ($$PWD/...)"""
    rel_path = os.path.relpath(abs_path, base_dir)
    # 统一使用正斜杠
    rel_path = rel_path.replace("\\", "/")
    return f"{QMAKE_PWD}/{rel_path}"

def main():
    if not os.path.exists(OCR_LIB):
        print(f"[ERROR] OCR 静态库不存在: {OCR_LIB}")
        print("        请先从 RapidOcrEmbed 复制 RapidOcrOnnxStatic.lib 到本目录")
        sys.exit(1)

    ort_libs = [os.path.basename(p) for p in glob.glob(os.path.join(ORT_DIR, "*.lib"))]
    ort_libs = [l for l in ort_libs if l not in EXCLUDE_ORT]
    ort_libs.sort()

    opencv_libs = sorted(os.path.basename(p) for p in glob.glob(os.path.join(OPENCV_DIR, "*.lib")))
    opencv_libs = [l for l in opencv_libs if l not in EXCLUDE_OPENCV]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by gen_libs_pri.py - DO NOT EDIT\n")
        f.write("# All static libs for single-file OcrQtCpp.exe\n")
        f.write("# 使用相对路径，方便项目迁移\n\n")
        # OCR 静态库 (本目录, 依赖 ORT + OpenCV, 放最前)
        f.write(f'LIBS += "{to_qmake_rel(OCR_LIB, HERE)}"\n\n')
        # MNN 静态库 (MNN 版本 OCR 依赖)
        if os.path.exists(MNN_LIB):
            f.write(f'LIBS += "{to_qmake_rel(MNN_LIB, HERE)}"\n\n')
        # Qt JPEG 插件 (必须在 mupdf.lib 之前，避免符号冲突)
        if os.path.exists(QT_JPEG_LIB):
            f.write("# Qt JPEG 插件 (优先链接，避免与 MuPDF JPEG 符号冲突)\n")
            f.write("# 可通过环境变量 QT_STATIC_PATH 指定 Qt 静态库路径\n")
            # Qt 路径保持绝对路径或使用环境变量
            qt_jpeg_fwd = QT_JPEG_LIB.replace("\\", "/")
            f.write(f'LIBS += "{qt_jpeg_fwd}"\n\n')
        # MuPDF 静态库
        if os.path.exists(MUPDF_LIB):
            f.write(f'LIBS += "{to_qmake_rel(MUPDF_LIB, HERE)}"\n\n')
        f.write("# ONNX Runtime static libs (alphabetical order)\n")
        for l in ort_libs:
            f.write(f'LIBS += "{to_qmake_rel(os.path.join(ORT_DIR, l), HERE)}"\n')
        f.write("\n# OpenCV static libs (libjpeg-turbo 已排除, 避免与 Qt JPEG 冲突)\n")
        for l in opencv_libs:
            f.write(f'LIBS += "{to_qmake_rel(os.path.join(OPENCV_DIR, l), HERE)}"\n')

    print(f"Generated: {OUT}")
    print(f"  OCR lib: {OCR_LIB} ({os.path.getsize(OCR_LIB)/1024/1024:.1f} MB)")
    print(f"  ORT libs: {len(ort_libs)}")
    print(f"  OpenCV libs: {len(opencv_libs)} (libjpeg-turbo excluded)")


if __name__ == "__main__":
    import sys
    main()
